### ISSUE TITLE
0.4.0 compatibility

### ISSUE THREAD

**Issue by crm114** [F4-Group/dokku-apt#11]
apt-get no longer works in dokku 0.4.0. Any ideas on how to make this plugin 0.4.0 compatible?

**Comment by Cactusbone** [comment]
Looks like pre-build-buildstep got deprecated
pre-build-buildpack seems to be the way to go now

**Comment by Cactusbone** [comment]
fixed by 97c65c88b1b70d3452ca2aac57a78c36042a1238
