### ISSUE TITLE
Adding repository fails with: `Error: '' invalid`

### ISSUE THREAD

**Issue by benmarten** [F4-Group/dokku-apt#16]
I have created a file called `apt-repositories` in the root of my project, with this content:

```
ppa:ubuntu-toolchain-r/test
```

There is a new line at then end of the file.
On pushing to dock, it seems to be added fine, but fails with the last line being `Error: '' invalid`

```
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
remote: gpg: keyring `/tmp/tmp51y68o64/secring.gpg' created
remote: gpg: keyring `/tmp/tmp51y68o64/pubring.gpg' created
remote: gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
remote: gpg: /tmp/tmp51y68o64/trustdb.gpg: trustdb created
remote: gpg: key BA9EF27F: public key "Launchpad Toolchain builds" imported
remote: gpg: Total number processed: 1
remote: gpg:               imported: 1  (RSA: 1)
OK
Error: '' invalid
```

Any ideas?

So doing this manually seems to work:

```
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.19.0-59-generic x86_64)
ben@box1:~$ export DEBIAN_FRONTEND=noninteractive
ben@box1:~$ sudo apt-get update
Ign http://us-central1.gce.archive.ubuntu.com trusty InRelease
[...]
Fetched 3,412 kB in 3s (919 kB/s)                           
Reading package lists... Done
ben@box1:~$ sudo apt-get install -y software-properties-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
ben@box1:~$ sudo add-apt-repository -y "ppa:ubuntu-toolchain-r/test"
gpg: keyring `/tmp/tmpg5ojrsa9/secring.gpg' created
gpg: keyring `/tmp/tmpg5ojrsa9/pubring.gpg' created
gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpg5ojrsa9/trustdb.gpg: trustdb created
gpg: key BA9EF27F: public key "Launchpad Toolchain builds" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
ben@box1:~$ 
```

I cannot find any trace about this error string in this project. Might be coming from dokku/docker directly?

**Comment by carlossless** [comment]
Any solutions found?

**Comment by cmmartin** [comment]
@jazzzz Any ideas at all on this one? I can't figure out where the error is even coming from, let alone how to fix it

**Comment by jazzzz** [comment]
I have no ideas, I could not reproduce it.

**Comment by cmmartin** [comment]
I am able to reproduce this by adding an extra line break in the file. Each line must have a **single** trailing line break. If you view your file with `cat -e`, you can see line breaks represented by the `$` character. I can pretty much guarantee your file looks like this...

```
ppa:ubuntu-toolchain-r/test$
$
```

The second line-break causes the script to think that we are installing two repositories, `'ppa:ubuntu-toolchain-r/test$'` and `''`. Hence the seemingly cryptic error message `Error: '' invalid`

I sent a [pull request](https://github.com/F4-Group/dokku-apt/pull/18) to ignore packages that are empty strings
