### ISSUE TITLE
Again installs the packages during deploy

### ISSUE THREAD

**Issue by misteral** [F4-Group/dokku-apt#6]
I am new to Dokker and Dokku. My Rails application requires several packages including java-7-jdk. When app re-deploy, all the packages installs again,  deploy ->  again installs all packages. So it should be? Docker not saves state?

**Comment by jazzzz** [comment]
Yes it's normal, dokku creates a new container everytime you push. Maybe you should use a custom buildpack, see http://progrium.viewdocs.io/dokku/application-deployment
